#!/bin/bash

### BEGIN INIT INFO
# Provides: Skywalker
# Required-Start: $network $remote_fs $time
# Required-Stop: $network $remote $time
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: start and stop Barbie software system
# Description:
### END INIT INFO

start() {
    echo -n "Starting NSL Stratospheric Balloon Payload framework..."
    daemon --name=xlauncher --respawn                                                                    xlauncher
    daemon --name=gps       --respawn 				       --stderr=/var/log/stderr_gps.log  gps_process
    echo " done."
}
# Restart the service
stop() {
    echo -n "Stopping NSL Stratospheric Balloon Payload framework..."
    daemon --name=gps  --stop
    daemon --name=xlauncher --stop
    kill -9 $(pidof xlauncher gps_process vitow_tx) > /dev/null 2>&1
    echo " done."
}
### main logic ###
case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart|reload)
        stop
        start
        ;;
    *)
        echo $"Usage: $0 {start|stop|restart|reload}"
        exit 1
esac
exit 0
